/**
 * Mail-Hub API
 * This is a specification for Mail-Hub API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@mail-hub.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DestinationMailbox model module.
 * @module model/DestinationMailbox
 * @version 0.8.0
 */
class DestinationMailbox {
    /**
     * Constructs a new <code>DestinationMailbox</code>.
     * @alias module:model/DestinationMailbox
     */
    constructor() { 
        
        DestinationMailbox.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DestinationMailbox</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DestinationMailbox} obj Optional instance to populate.
     * @return {module:model/DestinationMailbox} The populated <code>DestinationMailbox</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DestinationMailbox();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('verified')) {
                obj['verified'] = ApiClient.convertToType(data['verified'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
DestinationMailbox.prototype['id'] = undefined;

/**
 * @member {String} name
 */
DestinationMailbox.prototype['name'] = undefined;

/**
 * @member {Boolean} verified
 */
DestinationMailbox.prototype['verified'] = undefined;






export default DestinationMailbox;

