/**
 * Mail-Hub API
 * This is a specification for Mail-Hub API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@mail-hub.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject1 model module.
 * @module model/InlineObject1
 * @version 0.8.0
 */
class InlineObject1 {
    /**
     * Constructs a new <code>InlineObject1</code>.
     * @alias module:model/InlineObject1
     * @param catchAll {Boolean} 
     * @param defaultFwdThreshold {Number} 
     */
    constructor(catchAll, defaultFwdThreshold) { 
        
        InlineObject1.initialize(this, catchAll, defaultFwdThreshold);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, catchAll, defaultFwdThreshold) { 
        obj['catchAll'] = catchAll;
        obj['defaultFwdThreshold'] = defaultFwdThreshold;
    }

    /**
     * Constructs a <code>InlineObject1</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject1} obj Optional instance to populate.
     * @return {module:model/InlineObject1} The populated <code>InlineObject1</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject1();

            if (data.hasOwnProperty('catchAll')) {
                obj['catchAll'] = ApiClient.convertToType(data['catchAll'], 'Boolean');
            }
            if (data.hasOwnProperty('defaultFwdThreshold')) {
                obj['defaultFwdThreshold'] = ApiClient.convertToType(data['defaultFwdThreshold'], 'Number');
            }
            if (data.hasOwnProperty('fwd_addresses')) {
                obj['fwd_addresses'] = ApiClient.convertToType(data['fwd_addresses'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} catchAll
 */
InlineObject1.prototype['catchAll'] = undefined;

/**
 * @member {Number} defaultFwdThreshold
 */
InlineObject1.prototype['defaultFwdThreshold'] = undefined;

/**
 * IDs of destination mailboxes or blank array to remove all destination mailboxes
 * @member {Array.<Number>} fwd_addresses
 */
InlineObject1.prototype['fwd_addresses'] = undefined;






export default InlineObject1;

