/**
 * Mail-Hub API
 * This is a specification for Mail-Hub API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@mail-hub.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse2006Pages model module.
 * @module model/InlineResponse2006Pages
 * @version 0.8.0
 */
class InlineResponse2006Pages {
    /**
     * Constructs a new <code>InlineResponse2006Pages</code>.
     * @alias module:model/InlineResponse2006Pages
     */
    constructor() { 
        
        InlineResponse2006Pages.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse2006Pages</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse2006Pages} obj Optional instance to populate.
     * @return {module:model/InlineResponse2006Pages} The populated <code>InlineResponse2006Pages</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2006Pages();

            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('page')) {
                obj['page'] = ApiClient.convertToType(data['page'], 'Number');
            }
            if (data.hasOwnProperty('perPage')) {
                obj['perPage'] = ApiClient.convertToType(data['perPage'], 'Number');
            }
            if (data.hasOwnProperty('lastPage')) {
                obj['lastPage'] = ApiClient.convertToType(data['lastPage'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} total
 */
InlineResponse2006Pages.prototype['total'] = undefined;

/**
 * @member {Number} page
 */
InlineResponse2006Pages.prototype['page'] = undefined;

/**
 * @member {Number} perPage
 */
InlineResponse2006Pages.prototype['perPage'] = undefined;

/**
 * @member {Number} lastPage
 */
InlineResponse2006Pages.prototype['lastPage'] = undefined;






export default InlineResponse2006Pages;

