/**
 * Mail-Hub API
 * This is a specification for Mail-Hub API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@mail-hub.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject7 model module.
 * @module model/InlineObject7
 * @version 0.8.0
 */
class InlineObject7 {
    /**
     * Constructs a new <code>InlineObject7</code>.
     * @alias module:model/InlineObject7
     * @param fname {String} 
     * @param lname {String} 
     * @param password {String} Require strong password. At least 8 characters length. At least: 1 uppercase alphabetical character,  1 lowercase alphabetical character, 1 number, 1 special character. 
     * @param code {String} invitation code
     */
    constructor(fname, lname, password, code) { 
        
        InlineObject7.initialize(this, fname, lname, password, code);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, fname, lname, password, code) { 
        obj['fname'] = fname;
        obj['lname'] = lname;
        obj['password'] = password;
        obj['code'] = code;
    }

    /**
     * Constructs a <code>InlineObject7</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject7} obj Optional instance to populate.
     * @return {module:model/InlineObject7} The populated <code>InlineObject7</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject7();

            if (data.hasOwnProperty('fname')) {
                obj['fname'] = ApiClient.convertToType(data['fname'], 'String');
            }
            if (data.hasOwnProperty('lname')) {
                obj['lname'] = ApiClient.convertToType(data['lname'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} fname
 */
InlineObject7.prototype['fname'] = undefined;

/**
 * @member {String} lname
 */
InlineObject7.prototype['lname'] = undefined;

/**
 * Require strong password. At least 8 characters length. At least: 1 uppercase alphabetical character,  1 lowercase alphabetical character, 1 number, 1 special character. 
 * @member {String} password
 */
InlineObject7.prototype['password'] = undefined;

/**
 * invitation code
 * @member {String} code
 */
InlineObject7.prototype['code'] = undefined;






export default InlineObject7;

