/**
 * Mail-Hub API
 * This is a specification for Mail-Hub API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@mail-hub.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject2 model module.
 * @module model/InlineObject2
 * @version 0.8.0
 */
class InlineObject2 {
    /**
     * Constructs a new <code>InlineObject2</code>.
     * @alias module:model/InlineObject2
     * @param fname {String} 
     * @param lname {String} 
     * @param email {String} email address of user
     * @param password {String} Require strong password. At least 8 characters length. At least: 1 uppercase alphabetical character,  1 lowercase alphabetical character, 1 number, 1 special character. 
     */
    constructor(fname, lname, email, password) { 
        
        InlineObject2.initialize(this, fname, lname, email, password);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, fname, lname, email, password) { 
        obj['fname'] = fname;
        obj['lname'] = lname;
        obj['email'] = email;
        obj['password'] = password;
    }

    /**
     * Constructs a <code>InlineObject2</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject2} obj Optional instance to populate.
     * @return {module:model/InlineObject2} The populated <code>InlineObject2</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject2();

            if (data.hasOwnProperty('fname')) {
                obj['fname'] = ApiClient.convertToType(data['fname'], 'String');
            }
            if (data.hasOwnProperty('lname')) {
                obj['lname'] = ApiClient.convertToType(data['lname'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} fname
 */
InlineObject2.prototype['fname'] = undefined;

/**
 * @member {String} lname
 */
InlineObject2.prototype['lname'] = undefined;

/**
 * email address of user
 * @member {String} email
 */
InlineObject2.prototype['email'] = undefined;

/**
 * Require strong password. At least 8 characters length. At least: 1 uppercase alphabetical character,  1 lowercase alphabetical character, 1 number, 1 special character. 
 * @member {String} password
 */
InlineObject2.prototype['password'] = undefined;






export default InlineObject2;

