/**
 * Mail-Hub API
 * This is a specification for Mail-Hub API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@mail-hub.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Attachment from './Attachment';

/**
 * The Mail model module.
 * @module model/Mail
 * @version 0.8.0
 */
class Mail {
    /**
     * Constructs a new <code>Mail</code>.
     * @alias module:model/Mail
     */
    constructor() { 
        
        Mail.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Mail</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Mail} obj Optional instance to populate.
     * @return {module:model/Mail} The populated <code>Mail</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Mail();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('mail_address')) {
                obj['mail_address'] = ApiClient.convertToType(data['mail_address'], 'String');
            }
            if (data.hasOwnProperty('dest_name')) {
                obj['dest_name'] = ApiClient.convertToType(data['dest_name'], 'String');
            }
            if (data.hasOwnProperty('dest_domain')) {
                obj['dest_domain'] = ApiClient.convertToType(data['dest_domain'], 'String');
            }
            if (data.hasOwnProperty('mail_address_hash')) {
                obj['mail_address_hash'] = ApiClient.convertToType(data['mail_address_hash'], 'String');
            }
            if (data.hasOwnProperty('from_address')) {
                obj['from_address'] = ApiClient.convertToType(data['from_address'], 'String');
            }
            if (data.hasOwnProperty('subject')) {
                obj['subject'] = ApiClient.convertToType(data['subject'], 'String');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('html')) {
                obj['html'] = ApiClient.convertToType(data['html'], 'String');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Number');
            }
            if (data.hasOwnProperty('attachments')) {
                obj['attachments'] = ApiClient.convertToType(data['attachments'], [Attachment]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Mail.prototype['id'] = undefined;

/**
 * @member {String} mail_address
 */
Mail.prototype['mail_address'] = undefined;

/**
 * @member {String} dest_name
 */
Mail.prototype['dest_name'] = undefined;

/**
 * @member {String} dest_domain
 */
Mail.prototype['dest_domain'] = undefined;

/**
 * @member {String} mail_address_hash
 */
Mail.prototype['mail_address_hash'] = undefined;

/**
 * @member {String} from_address
 */
Mail.prototype['from_address'] = undefined;

/**
 * @member {String} subject
 */
Mail.prototype['subject'] = undefined;

/**
 * Text version of mail body if exists
 * @member {String} text
 */
Mail.prototype['text'] = undefined;

/**
 * HTML version of mail body if exists
 * @member {String} html
 */
Mail.prototype['html'] = undefined;

/**
 * @member {Number} timestamp
 */
Mail.prototype['timestamp'] = undefined;

/**
 * Short information of attachments
 * @member {Array.<module:model/Attachment>} attachments
 */
Mail.prototype['attachments'] = undefined;






export default Mail;

