/**
 * Mail-Hub API
 * This is a specification for Mail-Hub API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@mail-hub.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OneAttachment model module.
 * @module model/OneAttachment
 * @version 0.8.0
 */
class OneAttachment {
    /**
     * Constructs a new <code>OneAttachment</code>.
     * @alias module:model/OneAttachment
     */
    constructor() { 
        
        OneAttachment.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OneAttachment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OneAttachment} obj Optional instance to populate.
     * @return {module:model/OneAttachment} The populated <code>OneAttachment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OneAttachment();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('contentType')) {
                obj['contentType'] = ApiClient.convertToType(data['contentType'], 'String');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('cid')) {
                obj['cid'] = ApiClient.convertToType(data['cid'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
OneAttachment.prototype['name'] = undefined;

/**
 * @member {String} content
 */
OneAttachment.prototype['content'] = undefined;

/**
 * @member {String} contentType
 */
OneAttachment.prototype['contentType'] = undefined;

/**
 * @member {Number} size
 */
OneAttachment.prototype['size'] = undefined;

/**
 * @member {String} cid
 */
OneAttachment.prototype['cid'] = undefined;






export default OneAttachment;

