/**
 * Mail-Hub API
 * This is a specification for Mail-Hub API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@mail-hub.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OneDomainAllOfDomainForwards model module.
 * @module model/OneDomainAllOfDomainForwards
 * @version 0.8.0
 */
class OneDomainAllOfDomainForwards {
    /**
     * Constructs a new <code>OneDomainAllOfDomainForwards</code>.
     * @alias module:model/OneDomainAllOfDomainForwards
     */
    constructor() { 
        
        OneDomainAllOfDomainForwards.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OneDomainAllOfDomainForwards</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OneDomainAllOfDomainForwards} obj Optional instance to populate.
     * @return {module:model/OneDomainAllOfDomainForwards} The populated <code>OneDomainAllOfDomainForwards</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OneDomainAllOfDomainForwards();

            if (data.hasOwnProperty('domain_id')) {
                obj['domain_id'] = ApiClient.convertToType(data['domain_id'], 'Number');
            }
            if (data.hasOwnProperty('dest_addr_id')) {
                obj['dest_addr_id'] = ApiClient.convertToType(data['dest_addr_id'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} domain_id
 */
OneDomainAllOfDomainForwards.prototype['domain_id'] = undefined;

/**
 * @member {Number} dest_addr_id
 */
OneDomainAllOfDomainForwards.prototype['dest_addr_id'] = undefined;






export default OneDomainAllOfDomainForwards;

