/**
 * Mail-Hub API
 * This is a specification for Mail-Hub API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@mail-hub.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OneDomainAllOfDomainForwards from './OneDomainAllOfDomainForwards';

/**
 * The OneDomainAllOf model module.
 * @module model/OneDomainAllOf
 * @version 0.8.0
 */
class OneDomainAllOf {
    /**
     * Constructs a new <code>OneDomainAllOf</code>.
     * @alias module:model/OneDomainAllOf
     */
    constructor() { 
        
        OneDomainAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OneDomainAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OneDomainAllOf} obj Optional instance to populate.
     * @return {module:model/OneDomainAllOf} The populated <code>OneDomainAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OneDomainAllOf();

            if (data.hasOwnProperty('domainForwards')) {
                obj['domainForwards'] = ApiClient.convertToType(data['domainForwards'], [OneDomainAllOfDomainForwards]);
            }
        }
        return obj;
    }


}

/**
 * Short information of domain dest addresses
 * @member {Array.<module:model/OneDomainAllOfDomainForwards>} domainForwards
 */
OneDomainAllOf.prototype['domainForwards'] = undefined;






export default OneDomainAllOf;

