/**
 * Mail-Hub API
 * This is a specification for Mail-Hub API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@mail-hub.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Source model module.
 * @module model/Source
 * @version 0.8.0
 */
class Source {
    /**
     * Constructs a new <code>Source</code>.
     * @alias module:model/Source
     */
    constructor() { 
        
        Source.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Source</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Source} obj Optional instance to populate.
     * @return {module:model/Source} The populated <code>Source</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Source();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('mail_address')) {
                obj['mail_address'] = ApiClient.convertToType(data['mail_address'], 'String');
            }
            if (data.hasOwnProperty('dest_name')) {
                obj['dest_name'] = ApiClient.convertToType(data['dest_name'], 'String');
            }
            if (data.hasOwnProperty('dest_domain')) {
                obj['dest_domain'] = ApiClient.convertToType(data['dest_domain'], 'String');
            }
            if (data.hasOwnProperty('mail_address_hash')) {
                obj['mail_address_hash'] = ApiClient.convertToType(data['mail_address_hash'], 'String');
            }
            if (data.hasOwnProperty('source')) {
                obj['source'] = ApiClient.convertToType(data['source'], 'String');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Source.prototype['id'] = undefined;

/**
 * @member {String} mail_address
 */
Source.prototype['mail_address'] = undefined;

/**
 * @member {String} dest_name
 */
Source.prototype['dest_name'] = undefined;

/**
 * @member {String} dest_domain
 */
Source.prototype['dest_domain'] = undefined;

/**
 * @member {String} mail_address_hash
 */
Source.prototype['mail_address_hash'] = undefined;

/**
 * @member {String} source
 */
Source.prototype['source'] = undefined;

/**
 * @member {Number} timestamp
 */
Source.prototype['timestamp'] = undefined;






export default Source;

