/**
 * Mail-Hub API
 * This is a specification for Mail-Hub API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@mail-hub.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MailHubApi);
  }
}(this, function(expect, MailHubApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MailHubApi.Mail();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Mail', function() {
    it('should create an instance of Mail', function() {
      // uncomment below and update the code to test Mail
      //var instane = new MailHubApi.Mail();
      //expect(instance).to.be.a(MailHubApi.Mail);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new MailHubApi.Mail();
      //expect(instance).to.be();
    });

    it('should have the property mailAddress (base name: "mail_address")', function() {
      // uncomment below and update the code to test the property mailAddress
      //var instane = new MailHubApi.Mail();
      //expect(instance).to.be();
    });

    it('should have the property destName (base name: "dest_name")', function() {
      // uncomment below and update the code to test the property destName
      //var instane = new MailHubApi.Mail();
      //expect(instance).to.be();
    });

    it('should have the property destDomain (base name: "dest_domain")', function() {
      // uncomment below and update the code to test the property destDomain
      //var instane = new MailHubApi.Mail();
      //expect(instance).to.be();
    });

    it('should have the property mailAddressHash (base name: "mail_address_hash")', function() {
      // uncomment below and update the code to test the property mailAddressHash
      //var instane = new MailHubApi.Mail();
      //expect(instance).to.be();
    });

    it('should have the property fromAddress (base name: "from_address")', function() {
      // uncomment below and update the code to test the property fromAddress
      //var instane = new MailHubApi.Mail();
      //expect(instance).to.be();
    });

    it('should have the property subject (base name: "subject")', function() {
      // uncomment below and update the code to test the property subject
      //var instane = new MailHubApi.Mail();
      //expect(instance).to.be();
    });

    it('should have the property text (base name: "text")', function() {
      // uncomment below and update the code to test the property text
      //var instane = new MailHubApi.Mail();
      //expect(instance).to.be();
    });

    it('should have the property html (base name: "html")', function() {
      // uncomment below and update the code to test the property html
      //var instane = new MailHubApi.Mail();
      //expect(instance).to.be();
    });

    it('should have the property timestamp (base name: "timestamp")', function() {
      // uncomment below and update the code to test the property timestamp
      //var instane = new MailHubApi.Mail();
      //expect(instance).to.be();
    });

    it('should have the property attachments (base name: "attachments")', function() {
      // uncomment below and update the code to test the property attachments
      //var instane = new MailHubApi.Mail();
      //expect(instance).to.be();
    });

  });

}));
