/**
 * Mail-Hub API
 * This is a specification for Mail-Hub API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@mail-hub.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MailHubApi);
  }
}(this, function(expect, MailHubApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MailHubApi.DomainsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DomainsApi', function() {
    describe('domainsGet', function() {
      it('should call domainsGet successfully', function(done) {
        //uncomment below and update the code to test domainsGet
        //instance.domainsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('domainsIdDelete', function() {
      it('should call domainsIdDelete successfully', function(done) {
        //uncomment below and update the code to test domainsIdDelete
        //instance.domainsIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('domainsIdGet', function() {
      it('should call domainsIdGet successfully', function(done) {
        //uncomment below and update the code to test domainsIdGet
        //instance.domainsIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('domainsIdPut', function() {
      it('should call domainsIdPut successfully', function(done) {
        //uncomment below and update the code to test domainsIdPut
        //instance.domainsIdPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('domainsNameNameGet', function() {
      it('should call domainsNameNameGet successfully', function(done) {
        //uncomment below and update the code to test domainsNameNameGet
        //instance.domainsNameNameGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('domainsPost', function() {
      it('should call domainsPost successfully', function(done) {
        //uncomment below and update the code to test domainsPost
        //instance.domainsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('infoBasedomainsGet', function() {
      it('should call infoBasedomainsGet successfully', function(done) {
        //uncomment below and update the code to test infoBasedomainsGet
        //instance.infoBasedomainsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('infoDomainGet', function() {
      it('should call infoDomainGet successfully', function(done) {
        //uncomment below and update the code to test infoDomainGet
        //instance.infoDomainGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
