/**
 * Mail-Hub API
 * This is a specification for Mail-Hub API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@mail-hub.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MailHubApi);
  }
}(this, function(expect, MailHubApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MailHubApi.MailsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MailsApi', function() {
    describe('mailsGet', function() {
      it('should call mailsGet successfully', function(done) {
        //uncomment below and update the code to test mailsGet
        //instance.mailsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('mailsIdAttachmentsAttachmentIdGet', function() {
      it('should call mailsIdAttachmentsAttachmentIdGet successfully', function(done) {
        //uncomment below and update the code to test mailsIdAttachmentsAttachmentIdGet
        //instance.mailsIdAttachmentsAttachmentIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('mailsIdAttachmentsGet', function() {
      it('should call mailsIdAttachmentsGet successfully', function(done) {
        //uncomment below and update the code to test mailsIdAttachmentsGet
        //instance.mailsIdAttachmentsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('mailsIdDelete', function() {
      it('should call mailsIdDelete successfully', function(done) {
        //uncomment below and update the code to test mailsIdDelete
        //instance.mailsIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('mailsIdGet', function() {
      it('should call mailsIdGet successfully', function(done) {
        //uncomment below and update the code to test mailsIdGet
        //instance.mailsIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('mailsIdSourcesGet', function() {
      it('should call mailsIdSourcesGet successfully', function(done) {
        //uncomment below and update the code to test mailsIdSourcesGet
        //instance.mailsIdSourcesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
